skeleton/config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create]

  resource :session, only: [:new, :create, :destroy]

  resources :links do 
    resources :comments, only: [:create]
  end

  resources :comments, only: [:destroy]
end

skeleton/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

skeleton/app/models/comment.rb
class Comment < ApplicationRecord
    validates :body, :user_id, :link_id, presence: true
    
    belongs_to :user
    belongs_to :link
end

skeleton/app/models/link.rb
class Link < ApplicationRecord

    validates :url, :user_id, :title, presence: true

    belongs_to :user
    has_many :comments
end

skeleton/app/models/user.rb
class User < ApplicationRecord
    validates :username, :session_token, :password_digest, presence: true
    validates :password, length: {minimum: 6, allow_nil: true}

    after_initialize :ensure_session_token
    
    has_many :links
    has_many :comments

    attr_reader :password

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        user && user.is_password?(password) ? user : nil 
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password) 
    end

    def reset_session_token
        self.session_token = SecureRandom.urlsafe_base64
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= SecureRandom.urlsafe_base64
    end
end

skeleton/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])   
  end

  def ensure_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def log_in(user)
    session[:session_token] = user.reset_session_token
    @current_user = user
  end

  def log_out
    current_user.reset_session_token
    session[:session_token] = nil
    # @current_user = nil
  end

  def logged_in?
    !!current_user
  end
end

skeleton/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :ensure_logged_in

    def new
        @comment = Comment.new
    end


    def create
        @comment = Comment.new(comment_params)
        @comment.link_id = params[:link_id]
        @comment.user_id = current_user.id
        if @comment.save
            redirect_to link_url(@comment.link)
        else
            flash.now[:errors] = @comment.errors.full_messages
            render :new
        end
    end

    def destroy
        @comment = Comment.find(params[:id])
        @comment.destroy
        redirect_to link_url(@comment.link)
    end


    def comment_params
        params.require(:comment).permit(:body)
    end

end

skeleton/app/controllers/links_controller.rb
class LinksController < ApplicationController

    before_action :ensure_logged_in

    def new
        @link = Link.new
    end

    def index
        @links = Link.all
    end

    def create
        @link = Link.new(link_params)
        @link.user_id = current_user.id
        if @link.save
            redirect_to link_url(@link)
        else
            flash.now[:errors] = @link.errors.full_messages
            render :new
        end
    end

    def show
        @link = Link.find(params[:id])
    end

    def update
        @link = current_user.links.find(params[:id])
        if @link.update(link_params)
            redirect_to link_url(@link)
        else
            flash.now[:errors] = @link.errors.full_messages
            render :edit
        end
    end

    def edit
        @link = Link.find(params[:id])
        
    end

    def link_params
        params.require(:link).permit(:url, :title)
    end

end

skeleton/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new
    @user = User.new
  end

  def create
      user = User.find_by_credentials(params[:user][:username],
                                      params[:user][:password])
      if user
        log_in(user)
        redirect_to links_url
      else
        flash.now[:errors] = ['Invalid Username/Password']
        render :new
      end
  end

  def destroy
    log_out
    redirect_to new_session_url
  end
end

skeleton/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to links_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end  
  end
  
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

skeleton/app/helpers/application_helper.rb
module ApplicationHelper
end

skeleton/app/helpers/sessions_helper.rb
module SessionsHelper
end

skeleton/app/helpers/users_helper.rb
module UsersHelper
end

skeleton/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Authentication</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <%= current_user.username  %>

      <form action="<%= session_url %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Sign Out">
        </form>
       
    <% else %>
        <a href="<%= new_session_url %>">Sign In</a>
        <a href="<%= new_user_url %>">Sign Up</a>
      <% end %>

    <%= yield %>
    <% if flash[:errors] %>
    <%= flash[:errors].join("<br>")  %>
    <% end %>
  </body>
</html>

skeleton/app/views/links/edit.html.erb
<h1>Sign In</h1>

    <% if flash.now[:errors]  %>
    <% flash.now[:errors].each do |error| %>
            <%= error %>
            <% end %>
        <% end %>

            
<form action="<%= links_url(@link) %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">


    <label>Title<input type="text" name="link[title]" value="<%=@link.title%>">   
    </label>

    <label>URL<input type="text" name="link[url]" value="<%=@link.url%>">   
    </label>

    <input type="submit" value="Update Link">

</form>

skeleton/app/views/links/index.html.erb
<h2>New Link</h2>

<% @links.each do |link| %>

  <a href="<%=link_url(link) %>"><%= link.title %></a> : <%= link.url %>

<% end %>

skeleton/app/views/links/new.html.erb
<h2>New Link</h2>

<% if flash.now[:errors]  %>
    <% flash.now[:errors].each do |error| %>
    <%= error %>
    <% end %>
<% end %>
<form action="<%= links_url %>" method="Post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">


    <label>URL<input type="text" name="link[url]" value="<%= @link.url %>">   
    </label>

    <label>Title<input type="text" name="link[title]" value="<%= @link.title %>">   
    </label>

    <input type="submit" value="Create New Link">

</form>

skeleton/app/views/links/show.html.erb
<h2><%= @link.user.username %></h2>
<h2><%= @link.title %></h2>
<h2><%= @link.url %></h2>

    <% if flash.now[:errors]  %>
    <% flash.now[:errors].each do |error| %>
            <%= error %>
            <% end %>
            <% end %>

<a href="<%= links_url %>">Links</a>
<a href="<%= edit_link_url(@link) %>">Edit Link</a>

<form action="<%= link_comments_url(@link) %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>Add Comment
        <input type="text" name="comment[body]" value=""> 
    
    </label>

    <input type="submit" value="Add Comment">

</form>

skeleton/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

skeleton/app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>


<h1>Sign Up</h1>

<form action="<%= users_url %>" method="Post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">


    <label>Username<input type="text" name="user[username]" value="">   
    </label>

    <label>Password<input type="password" name="user[password]" value="">   
    </label>

    <input type="submit" value="Sign Up">

</form>